#!/usr/bin/env python
#       pyly.py written in python2.6
#       version 1.1
#       Copyright 2009 Mephiston <meph.snake@gmail.com>
#
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2.1.1 of the License, or
#       (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, get a copy on http://www.gnu.org/licenses/gpl.txt

# ---------------- Generic utilities ---------------- #
# The main purpose of this script is to easily give urls in bit.ly format.
# It shorts the url anonymously.
#    -------------------- TODO LIST -------------------- *
#    Adapt it for using graphical interface, plus of terminal.

import urllib
def shorten_url(long_url):
    try:
        longUrl = (long_url)
        encodeurl='http://bit.ly/%s' % (longUrl)
        request = urllib.urlopen(encodeurl)
        responde = request.read ()
        request.close()
        print (responde)
    except IOError, e:
        raise "urllib error"

if __name__ == '__main__':
    url =str(raw_input("Insert the url that you want to shorten: "))
    shorten_url(url)

