#!/usr/bin/python
from urllib import urlopen,urlencode
from exceptions import IndexError, IOError, KeyError
from sys import argv
#       pyly.py written in python2.6
#       version 1.3
#       Copyright 2009 Mephiston <meph.snake@gmail.com>
#
#       This program is free software; you can redistribute it and/or modify
#       it under the terms of the GNU General Public License as published by
#       the Free Software Foundation; either version 2.1.1 of the License, or
#       (at your option) any later version.
#
#       This program is distributed in the hope that it will be useful,
#       but WITHOUT ANY WARRANTY; without even the implied warranty of
#       MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#       GNU General Public License for more details.
#
#       You should have received a copy of the GNU General Public License
#       along with this program; if not, get a copy on http://www.gnu.org/licenses/gpl.txt

#------------------------------ Utilities --------------------------------------- #
# The main purpose of this script is to easily give urls with bit.ly service.
# It shorts the url with your user and apikey for having stadistics and all the benefits of registered.
#---------------------------- MayBeToDo LIST ------------------------------------ #
#    Adapt it for using graphical interface, plus of terminal.
#--------------------------- CHANGE LOG ----------------------------------------- #
#       1.0     Initial release
#       1.1     Fixed bugs, can use url with "&" atributes
#       1.2     Added a system argument function, you can choose between the sys.argv or ask function.
#               By changing the line 75 for sysRun(key,user) or askRun(key,user)
#       1.3     Fixed bugs, errors are treated as exceptions.
#--------------------------- TESTED IN ------------------------------------------ #
#       GNU/Linux (all distros)

def shorten_url(long_url, api_key, my_user):
    try:
        longUrl=urlencode(dict(longUrl=long_url))
        apiKey=urlencode(dict(apiKey=api_key))
        login=urlencode(dict(login=my_user))
        encodeurl='http://api.bit.ly/shorten?version=2.0.1&%s&%s&%s' % (longUrl, apiKey, login)
        request=urlopen(encodeurl)
        responde=request.read ()
        request.close()
        respondedict=eval(responde)
        #Here we make the requesting process.
        try:
            short_url=respondedict["results"][long_url]["shortUrl"]
            print short_url
        except KeyError:
            print 'The URL was not recognized.'
            #If the url is not recognized on the request, we treat it as an error.
    except IOError, e:
        raise 'Ops! An I/O error happened.'

def askRun(key,user):
    urll=str(raw_input('Insert the url that you want to shorten: '))
    if urll!='':
        shorten_url(urll, key, user)
    else:
        print 'The URL was not provided.'

def sysRun(key,user):
    #If you chose sysRun, it will use the url provided in your command line.
    try:
        shorten_url(argv[1], key, user)
    except IndexError:
        print 'The URL was not provided.'


try:
    if __name__ == '__main__':
        key=str('ENTER YOUR API KEY HERE.')
        user=str('ENTER YOUR USER HERE.')
        sysRun(key,user)
except KeyboardInterrupt:
    print '\nThe progam was interrupted.'